"""
⚠️ MASKING 처리된 파일

이 파일에 포함된 비즈니스 용어는 {{ko.json}} 키로 마스킹되어 있습니다.
원래 용어를 확인하려면 다음 파일을 참조하세요:
- frontend/src/locales/ko.json
"""
# Generated by Django 5.0.1 on 2026-04-29 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('notice', 'Notice'), ('release_note', 'Release Note')], max_length=20, verbose_name='템플릿')),
                ('date', models.DateField(verbose_name='날짜')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('items', models.JSONField(default=list, verbose_name='항목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='{{request.line}} 이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
            ],
            options={
                'verbose_name': '{{request.line}}',
                'verbose_name_plural': '{{request.line}} 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('category', models.CharField(choices=[('inquiry', '문의'), ('error_report', '오류 신고'), ('feature_request', '기능 제안'), ('task_request', '작업 요청')], max_length=20, verbose_name='유형')),
                ('submitter_name', models.CharField(max_length=100, verbose_name='제출자')),
                ('submitter_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('content', models.TextField(verbose_name='내용')),
                ('response', models.TextField(blank=True, verbose_name='답변')),
                ('status', models.CharField(choices=[('checking', '확인중'), ('completed', '완료'), ('rejected', '거부')], default='checking', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
            ],
            options={
                'verbose_name': 'VOC',
                'verbose_name_plural': 'VOC 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoStepS1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processid', models.CharField(max_length=200, verbose_name='{{request.process_id}} ID')),
                ('stepseq', models.CharField(max_length=200, verbose_name='{{request.col_step}}SEQ')),
                ('descript', models.CharField(max_length=200, verbose_name='{{request.process_selection}}명')),
                ('recipeid', models.CharField(max_length=200, verbose_name='Recipe ID')),
                ('areaname', models.CharField(max_length=50, verbose_name='영역명')),
                ('eqptype', models.CharField(max_length=50, verbose_name='장비 타입')),
                ('layerid', models.CharField(blank=True, max_length=200, verbose_name='레이어 ID')),
                ('updated', models.CharField(blank=True, max_length=50, verbose_name='업데이트')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': 'line1 {{request.col_step}} 정보',
                'verbose_name_plural': 'line1 {{request.col_step}} 정보 목록',
                'indexes': [models.Index(fields=['processid'], name='api_pstep_line1_processid_idx'), models.Index(fields=['processid', 'eqptype'], name='api_pstep_line1_prcid_eqp_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoStepS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processid', models.CharField(max_length=200, verbose_name='{{request.process_id}} ID')),
                ('stepseq', models.CharField(max_length=200, verbose_name='{{request.col_step}}SEQ')),
                ('descript', models.CharField(max_length=200, verbose_name='{{request.process_selection}}명')),
                ('recipeid', models.CharField(max_length=200, verbose_name='Recipe ID')),
                ('areaname', models.CharField(max_length=50, verbose_name='영역명')),
                ('eqptype', models.CharField(max_length=50, verbose_name='장비 타입')),
                ('layerid', models.CharField(blank=True, max_length=200, verbose_name='레이어 ID')),
                ('updated', models.CharField(blank=True, max_length=50, verbose_name='업데이트')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': 'line3 {{request.col_step}} 정보',
                'verbose_name_plural': 'line3 {{request.col_step}} 정보 목록',
                'indexes': [models.Index(fields=['processid'], name='api_pstep_line3_processid_idx'), models.Index(fields=['processid', 'eqptype'], name='api_pstep_line3_prcid_eqp_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoStepS4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processid', models.CharField(max_length=200, verbose_name='{{request.process_id}} ID')),
                ('stepseq', models.CharField(max_length=200, verbose_name='{{request.col_step}}SEQ')),
                ('descript', models.CharField(max_length=200, verbose_name='{{request.process_selection}}명')),
                ('recipeid', models.CharField(max_length=200, verbose_name='Recipe ID')),
                ('areaname', models.CharField(max_length=50, verbose_name='영역명')),
                ('eqptype', models.CharField(max_length=50, verbose_name='장비 타입')),
                ('layerid', models.CharField(blank=True, max_length=200, verbose_name='레이어 ID')),
                ('updated', models.CharField(blank=True, max_length=50, verbose_name='업데이트')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': 'line4 {{request.col_step}} 정보',
                'verbose_name_plural': 'line4 {{request.col_step}} 정보 목록',
                'indexes': [models.Index(fields=['processid'], name='api_pstep_line4_processid_idx'), models.Index(fields=['processid', 'eqptype'], name='api_pstep_line4_prcid_eqp_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoStepS5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processid', models.CharField(max_length=200, verbose_name='{{request.process_id}} ID')),
                ('stepseq', models.CharField(max_length=200, verbose_name='{{request.col_step}}SEQ')),
                ('descript', models.CharField(max_length=200, verbose_name='{{request.process_selection}}명')),
                ('recipeid', models.CharField(max_length=200, verbose_name='Recipe ID')),
                ('areaname', models.CharField(max_length=50, verbose_name='영역명')),
                ('eqptype', models.CharField(max_length=50, verbose_name='장비 타입')),
                ('layerid', models.CharField(blank=True, max_length=200, verbose_name='레이어 ID')),
                ('updated', models.CharField(blank=True, max_length=50, verbose_name='업데이트')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': 'line5 {{request.col_step}} 정보',
                'verbose_name_plural': 'line5 {{request.col_step}} 정보 목록',
                'indexes': [models.Index(fields=['processid'], name='api_pstep_line5_processid_idx'), models.Index(fields=['processid', 'eqptype'], name='api_pstep_line5_prcid_eqp_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, verbose_name='{{request.line}}')),
                ('process', models.CharField(max_length=200, verbose_name='{{request.process_selection}}')),
                ('product_name', models.CharField(max_length=200, verbose_name='{{request.partid_selection}}')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': '{{request.process_selection}}-{{request.partid_selection}} 캐시',
                'verbose_name_plural': '{{request.process_selection}}-{{request.partid_selection}} 캐시 목록',
                'indexes': [models.Index(fields=['line'], name='api_process_line_664ae4_idx'), models.Index(fields=['line', 'process'], name='api_process_line_978a8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductProcessId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50, verbose_name='{{request.line}}')),
                ('product_name', models.CharField(max_length=200, verbose_name='{{request.partid_selection}}')),
                ('process_id', models.CharField(max_length=200, verbose_name='{{request.process_id}}')),
                ('last_synced', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': '{{request.partid_selection}}-{{request.process_id}} 캐시',
                'verbose_name_plural': '{{request.partid_selection}}-{{request.process_id}} 캐시 목록',
                'indexes': [models.Index(fields=['line'], name='api_product_line_aba00c_idx'), models.Index(fields=['line', 'product_name'], name='api_product_line_a981f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='의뢰서 제목')),
                ('requester_name', models.CharField(max_length=100, verbose_name='의뢰자 이름')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='의뢰자 이메일')),
                ('requester_department', models.CharField(max_length=100, verbose_name='부서')),
                ('product_name', models.CharField(max_length=200, verbose_name='{{request.partid_selection}}')),
                ('reference_materials', models.TextField(blank=True, verbose_name='참고 자료')),
                ('additional_notes', models.TextField(blank=True, verbose_name='추가 정보(JSON)')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '상신됨'), ('under_review', '검토중'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='상신일')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='의뢰자')),
            ],
            options={
                'verbose_name': '의뢰서',
                'verbose_name_plural': '의뢰서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('R', '{{agent_R}}'), ('J', '{{agent_J}}'), ('O', '{{agent_O}}'), ('E', '{{agent_E}}')], max_length=2, verbose_name='담당 에이전트')),
                ('action', models.CharField(choices=[('pending', '대기'), ('approved', '합의'), ('rejected', '반려')], default='checking', max_length=10, verbose_name='결재 결과')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('is_parallel', models.BooleanField(default=False, verbose_name='병렬 처리 여부')),
                ('assignee_name', models.CharField(blank=True, max_length=100, verbose_name='담당자 이름')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='api.requestdocument', verbose_name='의뢰서')),
            ],
            options={
                'verbose_name': '결재 단계',
                'verbose_name_plural': '결재 단계 목록',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VocHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checking', '확인중'), ('completed', '완료'), ('rejected', '거부')], default='checking', max_length=20, verbose_name='처리 결과')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='처리일시')),
                ('comment', models.TextField(blank=True, verbose_name='의견')),
                ('assignee_name', models.CharField(blank=True, max_length=100, verbose_name='담당자 이름')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_voc_histories', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('voc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.voc', verbose_name='VOC')),
            ],
            options={
                'verbose_name': 'VOC 처리 이력',
                'verbose_name_plural': 'VOC 처리 이력 목록',
                'ordering': ['-acted_at'],
                'indexes': [models.Index(fields=['voc'], name='api_vochist_voc_idx'), models.Index(fields=['action'], name='api_vochist_action_idx')],
            },
        ),
        # auth_user 테이블에 role, department, display_name 필드 추가
        migrations.RunSQL(
            sql="""
            ALTER TABLE auth_user 
            ADD COLUMN role VARCHAR(10) NOT NULL DEFAULT 'NONE',
            ADD COLUMN department VARCHAR(200) NOT NULL DEFAULT '',
            ADD COLUMN display_name VARCHAR(100) NOT NULL DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE auth_user 
            DROP COLUMN role,
            DROP COLUMN department,
            DROP COLUMN display_name;
            """
        ),
    ]
