# Generated by Django 5.0.1 on 2026-04-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_stepinfo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='combinationproduct',
            new_name='api_combina_line_08884f_idx',
            old_name='api_combin_line_idx',
        ),
        migrations.RenameIndex(
            model_name='combinationproduct',
            new_name='api_combina_line_e082c3_idx',
            old_name='api_combin_line_comb_idx',
        ),
        migrations.RenameIndex(
            model_name='productcooking',
            new_name='api_product_line_3d794b_idx',
            old_name='api_prodco_line_idx',
        ),
        migrations.RenameIndex(
            model_name='productcooking',
            new_name='api_product_line_4f20ef_idx',
            old_name='api_prodco_line_prod_idx',
        ),
        migrations.RenameIndex(
            model_name='stepinfo',
            new_name='api_stepinf_line_7698b3_idx',
            old_name='api_stepinf_line_process_idx',
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('submitted', '상신됨'), ('under_review', '검토중'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=20, verbose_name='상태'),
        ),
    ]
