# Generated by Django 4.2.13 on 2026-08-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mailnotification_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='action',
            field=models.CharField(choices=[('pending', '대기'), ('approved', '합의'), ('rejected', '반려'), ('skip', '건너뜀')], default='pending', max_length=10, verbose_name='결재 결과'),
        ),
    ]
