# Generated by Django 4.2.13 on 2026-08-07 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_fix_usergroup_pk_bigint"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="shared_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_documents",
                to="api.usergroup",
                verbose_name="임시저장 공유 그룹",
            ),
        ),
    ]
