# Generated by Django 4.2.13 on 2026-08-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_requestdocument_shared_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewItemMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="항목 제목")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_review_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "검토 항목 마스터",
                "verbose_name_plural": "검토 항목 마스터 목록",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="항목 제목(사본)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="api.requestdocument",
                        verbose_name="의뢰서",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="api.reviewitemmaster",
                        verbose_name="마스터 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "의뢰서 검토 항목",
                "verbose_name_plural": "의뢰서 검토 항목 목록",
                "ordering": ["id"],
                "unique_together": {("document", "master")},
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewItemReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loginid",
                    models.CharField(max_length=150, verbose_name="검토자 로그인 ID"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="검토자 이름"
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="확인 여부"),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확인일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="지정일시"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewers",
                        to="api.documentreviewitem",
                        verbose_name="검토 항목",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_item_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
            ],
            options={
                "verbose_name": "검토 항목 검토자",
                "verbose_name_plural": "검토 항목 검토자 목록",
                "ordering": ["id"],
                "unique_together": {("item", "loginid")},
            },
        ),
    ]
