# Generated by Django 4.2.13 on 2026-08-11 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_reviewitemmaster_documentreviewitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_document_id",
                    models.IntegerField(verbose_name="원본 의뢰서 ID"),
                ),
                ("title", models.CharField(max_length=600, verbose_name="의뢰서 제목")),
                (
                    "product_name",
                    models.CharField(
                        max_length=200, verbose_name="{{request.partid_selection}}"
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=100, verbose_name="의뢰자 이름"),
                ),
                (
                    "requester_department",
                    models.CharField(blank=True, max_length=100, verbose_name="부서"),
                ),
                (
                    "requester_loginid",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="의뢰자 로그인 ID"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="상신일"),
                ),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="상세 정보(JSON)"),
                ),
                (
                    "approval_steps",
                    models.TextField(blank=True, verbose_name="결재 단계(JSON)"),
                ),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="반려된 회차"
                    ),
                ),
                ("rejected_at", models.DateTimeField(verbose_name="반려일시")),
                (
                    "rejected_agent",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="반려 단계"
                    ),
                ),
                (
                    "rejected_by_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="반려자 이름"
                    ),
                ),
                (
                    "rejected_by_loginid",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="반려자 로그인 ID"
                    ),
                ),
                (
                    "reject_comment",
                    models.TextField(blank=True, verbose_name="반려 사유"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="적재일시"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejection_snapshots",
                        to="api.requestdocument",
                        verbose_name="의뢰서",
                    ),
                ),
            ],
            options={
                "verbose_name": "반려 이력",
                "verbose_name_plural": "반려 이력 목록",
                "ordering": ["-rejected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-rejected_at"], name="api_rejecti_rejecte_981bd5_idx"
                    ),
                    models.Index(
                        fields=["source_document_id"],
                        name="api_rejecti_source__65eada_idx",
                    ),
                ],
            },
        ),
    ]
