# Generated by Django 4.2.13 on 2026-08-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_rejectionsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("stage_arrival", "단계 도착"),
                    ("rejected", "반려"),
                    ("approved", "승인 완료"),
                    ("notify_submitted", "상신 통보(통보처)"),
                    ("notify_approved", "결재 완료 통보(통보처)"),
                    ("withdraw_requested", "철회 요청"),
                    ("withdraw_completed", "철회 완료"),
                    ("withdraw_rejected", "철회 거부"),
                    ("withdraw_cancelled", "철회 요청 취소"),
                    ("voc_created", "VOC 등록"),
                    ("voc_comment", "VOC 댓글"),
                ],
                max_length=20,
                verbose_name="이벤트 유형",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="요청자 이름"
                    ),
                ),
                ("reason", models.TextField(verbose_name="철회 사유")),
                (
                    "round",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="요청 회차"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "요청됨"),
                            ("rejected", "거부됨"),
                            ("cancelled", "취소됨"),
                        ],
                        default="requested",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "target_step_ids",
                    models.JSONField(default=list, verbose_name="대상 단계 id"),
                ),
                (
                    "confirmed_step_ids",
                    models.JSONField(default=list, verbose_name="확인된 단계 id"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청일시"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="거부·취소일시"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdraw_requests",
                        to="api.requestdocument",
                        verbose_name="의뢰서",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="withdraw_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="요청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "철회 요청",
                "verbose_name_plural": "철회 요청 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
