# Generated by Django 4.2.13 on 2026-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_mailnotification_event_type_withdrawrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mail_lines",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="api.line",
                verbose_name="메일 수신 라인",
            ),
        ),
    ]
