# Generated by Django 4.2.13 on 2026-08-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_userprofile_mail_lines"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_all_mail",
            field=models.BooleanField(default=True, verbose_name="메일 전체 받기"),
        ),
    ]
