# Generated by Django 4.2.13 on 2026-08-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_userprofile_mail_lines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voc",
            name="submitter_user_id",
        ),
        migrations.RemoveField(
            model_name="voccomment",
            name="is_reject_reason",
        ),
        migrations.AddField(
            model_name="voc",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vocs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="제출자",
            ),
        ),
        migrations.AlterField(
            model_name="voc",
            name="status",
            field=models.CharField(
                choices=[("checking", "확인중"), ("completed", "완료")],
                default="checking",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="vochistory",
            name="action",
            field=models.CharField(
                choices=[("checking", "확인중"), ("completed", "완료")],
                default="checking",
                max_length=20,
                verbose_name="처리 결과",
            ),
        ),
    ]
