# Generated by Django 4.2.13 on 2026-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_userprofile_receive_all_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="agent",
            field=models.CharField(
                choices=[
                    ("PL", "검토"),
                    ("R", "{{agent_R}}"),
                    ("RV", "검토자"),
                    ("P", "{{agent_P}}"),
                    ("PV", "검토자"),
                    ("J", "{{agent_J}}"),
                    ("O", "{{agent_O}}"),
                    ("E", "{{agent_E}}"),
                    ("EV", "검토자"),
                    ("RA", "후결자"),
                    ("SA", "영업/기술지원 합의자"),
                ],
                max_length=2,
                verbose_name="담당 에이전트",
            ),
        ),
    ]
