# Generated by Django 4.2.13 on 2026-08-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # 0022 가 둘로 갈라져(receive_all_mail / VOC) 리프 노드가 2개가 됐다.
        # 건드리는 모델이 서로 달라 순서 의존이 없으므로, 이 파일을 0023 으로 내려
        # receive_all_mail 뒤에 직렬로 잇는다.
        ("api", "0022_userprofile_receive_all_mail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voc",
            name="submitter_user_id",
        ),
        migrations.RemoveField(
            model_name="voccomment",
            name="is_reject_reason",
        ),
        migrations.AddField(
            model_name="voc",
            name="submitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vocs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="제출자",
            ),
        ),
        migrations.AlterField(
            model_name="voc",
            name="status",
            field=models.CharField(
                choices=[("checking", "확인중"), ("completed", "완료")],
                default="checking",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="vochistory",
            name="action",
            field=models.CharField(
                choices=[("checking", "확인중"), ("completed", "완료")],
                default="checking",
                max_length=20,
                verbose_name="처리 결과",
            ),
        ),
    ]
