# Generated by Django 4.2.13 on 2026-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # main 병합 시 0023 이 둘(SA agent / VOC)로 갈라져 리프 노드가 2개가 됐다.
        # 건드리는 모델이 서로 달라 순서 의존이 없으므로, 이 파일을 0024 로 올려
        # VOC 마이그레이션 뒤에 직렬로 잇는다(0023_voc 가 쓴 해소 방식과 동일).
        ("api", "0023_voc_submitter_fk_remove_reject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="agent",
            field=models.CharField(
                choices=[
                    ("PL", "검토"),
                    ("R", "{{agent_R}}"),
                    ("RV", "검토자"),
                    ("P", "{{agent_P}}"),
                    ("PV", "검토자"),
                    ("J", "{{agent_J}}"),
                    ("O", "{{agent_O}}"),
                    ("E", "{{agent_E}}"),
                    ("EV", "검토자"),
                    ("RA", "후결자"),
                    ("SA", "영업/기술지원 합의자"),
                ],
                max_length=2,
                verbose_name="담당 에이전트",
            ),
        ),
    ]
