# Generated by Django 4.2.13 on 2026-08-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_approvalstep_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pauserequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("requested", "요청됨"),
                    ("confirmed", "중단됨"),
                    ("rejected", "거부됨"),
                    ("cancelled", "취소됨"),
                    ("resumed", "재개됨"),
                ],
                default="requested",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
