# Generated by Django 4.2.13 on 2026-08-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_mailnotification_event_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminnotice",
            options={
                "ordering": ["-is_pinned", "-date", "-created_at"],
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항 목록",
            },
        ),
        migrations.AddField(
            model_name="adminnotice",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="상단 고정"),
        ),
    ]
