# Generated by Django 4.2.13 on 2026-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_adminnotice_options_adminnotice_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerFilterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        choices=[("J", "J"), ("O", "O")],
                        max_length=1,
                        verbose_name="대상 표",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="필터 이름")),
                ("words", models.JSONField(default=dict, verbose_name="키워드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "J/O-layer 공유 필터",
                "verbose_name_plural": "J/O-layer 공유 필터",
                "ordering": ["table", "created_at"],
            },
        ),
    ]
