# Generated by Django 4.2.13 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_userprofile_receive_submit_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapname",
            name="AAA1",
            field=models.CharField(
                max_length=200, null=True, blank=True, verbose_name="AAA1"
            ),
        ),
        migrations.AddField(
            model_name="mapname",
            name="AAA2",
            field=models.CharField(
                max_length=200, null=True, blank=True, verbose_name="AAA2"
            ),
        ),
        migrations.AddField(
            model_name="mapname",
            name="AAA3",
            field=models.CharField(
                max_length=200, null=True, blank=True, verbose_name="AAA3"
            ),
        ),
    ]
