# Generated by Django 4.2.13 on 2026-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_mapname_aaa1_aaa2_aaa3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailnotification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("stage_arrival", "단계 도착"),
                    ("rejected", "반려"),
                    ("approved", "승인 완료"),
                    ("notify_submitted", "상신 통보(통보처)"),
                    ("notify_approved", "결재 완료 통보(통보처)"),
                    ("withdraw_requested", "철회 요청"),
                    ("withdraw_completed", "철회 완료"),
                    ("withdraw_rejected", "철회 거부"),
                    ("withdraw_cancelled", "철회 요청 취소"),
                    ("voc_created", "VOC 등록"),
                    ("voc_comment", "VOC 댓글"),
                    ("rtdb_sync_failed", "RTDB 동기화 실패"),
                    ("dcq_sync_failed", "DCQ 동기화 실패"),
                    ("notify_p_completed", "P 단계 완료 통보"),
                    ("revision_requested", "수정 요청"),
                    ("pause_requested", "중단 요청"),
                    ("pause_confirmed", "중단 확정"),
                    ("pause_rejected", "중단 거부"),
                    ("pause_resumed", "결재 재개"),
                    ("document_deleted", "의뢰서 삭제"),
                    ("post_approver_removed", "후결자 제외"),
                    ("validation_system_changed", "Validation System 변경"),
                ],
                max_length=32,
                verbose_name="이벤트 유형",
            ),
        ),
    ]
