# Generated by Django 4.2.13 on 2026-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_mailnotification_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="mail_completion_matched",
            field=models.BooleanField(
                default=False, verbose_name="완료 메일 매칭 여부"
            ),
        ),
    ]
