# Generated by Django 4.2.13 on 2026-09-07 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_mail_completion_matched"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalMarkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="범주 이름")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("danger", "danger"),
                            ("warning", "warning"),
                            ("success", "success"),
                            ("accent", "accent"),
                            ("pause", "pause"),
                        ],
                        max_length=10,
                        verbose_name="범주 색(테마 색상 중 택1)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="표시 순서"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mark_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 마킹 범주",
                "verbose_name_plural": "개인 마킹 범주 목록",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalDocumentMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marks",
                        to="api.personalmarkcategory",
                        verbose_name="범주",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_marks",
                        to="api.requestdocument",
                        verbose_name="의뢰서",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_marks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "개인 의뢰서 마킹",
                "verbose_name_plural": "개인 의뢰서 마킹 목록",
                "unique_together": {("user", "document")},
            },
        ),
    ]
