# Generated by Django 4.2.13 on 2026-09-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_mailnotification_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoStepS5Ov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line5 {{request.col_step}} 정보(POVLAY)",
                "verbose_name_plural": "line5 {{request.col_step}} 정보(POVLAY) 목록",
                "db_table": "api_photosteps5_ov",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line5_ov_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS5Cd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line5 {{request.col_step}} 정보(XXXXXX)",
                "verbose_name_plural": "line5 {{request.col_step}} 정보(XXXXXX) 목록",
                "db_table": "api_photosteps5_cd",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line5_cd_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS4Ov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line4 {{request.col_step}} 정보(POVLAY)",
                "verbose_name_plural": "line4 {{request.col_step}} 정보(POVLAY) 목록",
                "db_table": "api_photosteps4_ov",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line4_ov_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS4Cd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line4 {{request.col_step}} 정보(XXXXXX)",
                "verbose_name_plural": "line4 {{request.col_step}} 정보(XXXXXX) 목록",
                "db_table": "api_photosteps4_cd",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line4_cd_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS3Ov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line3 {{request.col_step}} 정보(POVLAY)",
                "verbose_name_plural": "line3 {{request.col_step}} 정보(POVLAY) 목록",
                "db_table": "api_photosteps3_ov",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line3_ov_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS3Cd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line3 {{request.col_step}} 정보(XXXXXX)",
                "verbose_name_plural": "line3 {{request.col_step}} 정보(XXXXXX) 목록",
                "db_table": "api_photosteps3_cd",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line3_cd_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS1Ov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line1 {{request.col_step}} 정보(POVLAY)",
                "verbose_name_plural": "line1 {{request.col_step}} 정보(POVLAY) 목록",
                "db_table": "api_photosteps1_ov",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line1_ov_prcid_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PhotoStepS1Cd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "line1 {{request.col_step}} 정보(XXXXXX)",
                "verbose_name_plural": "line1 {{request.col_step}} 정보(XXXXXX) 목록",
                "db_table": "api_photosteps1_cd",
                "indexes": [
                    models.Index(
                        fields=["processid"], name="api_pstep_line1_cd_prcid_idx"
                    )
                ],
            },
        ),
    ]
