# Generated by Django 4.2.13 on 2026-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_photostep_ovl_extra_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoStepChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_run_id", models.UUIDField(verbose_name="동기화 실행 ID")),
                (
                    "line",
                    models.CharField(max_length=50, verbose_name="{{request.line}}"),
                ),
                (
                    "table_type",
                    models.CharField(
                        choices=[("ALL", "전체"), ("OV", "POVLAY"), ("CD", "XXXXXX")],
                        max_length=10,
                        verbose_name="테이블 구분",
                    ),
                ),
                (
                    "processid",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_id}} ID"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[("added", "추가"), ("removed", "삭제")],
                        max_length=10,
                        verbose_name="변경 종류",
                    ),
                ),
                (
                    "stepseq",
                    models.CharField(
                        max_length=200, verbose_name="{{request.col_step}}SEQ"
                    ),
                ),
                (
                    "descript",
                    models.CharField(
                        max_length=200, verbose_name="{{request.process_selection}}명"
                    ),
                ),
                (
                    "recipeid",
                    models.CharField(max_length=200, verbose_name="Recipe ID"),
                ),
                ("areaname", models.CharField(max_length=50, verbose_name="영역명")),
                ("eqptype", models.CharField(max_length=50, verbose_name="장비 타입")),
                (
                    "layerid",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="레이어 ID"
                    ),
                ),
                (
                    "updated",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="업데이트"
                    ),
                ),
                ("detected_at", models.DateTimeField(verbose_name="감지 시각")),
            ],
            options={
                "verbose_name": "{{request.col_step}} 변경 이력",
                "verbose_name_plural": "{{request.col_step}} 변경 이력 목록",
                "ordering": ["-detected_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["-detected_at"], name="api_pstep_chg_detected_idx"
                    ),
                    models.Index(
                        fields=["sync_run_id", "processid"],
                        name="api_pstep_chg_run_pid_idx",
                    ),
                ],
            },
        ),
    ]
