# Generated by Django 4.2.13 on 2026-09-11 03:26

from django.db import migrations, models

# api_photosteps{N} 이 eqptype 전체 혼재에서 PMAINF 전용으로 바뀌면서, 그 테이블의 변경 이력을
# 가리키던 table_type 코드값 'ALL'(전체) 도 'MF'(PMAINF) 로 바뀌었다. 이미 쌓여 있는 이력 행은
# 같은 테이블을 가리키므로 값만 치환한다 - 변경 현황 화면의 필터가 새 코드값만 보내기 때문에,
# 치환하지 않으면 기존 이력이 어느 필터로도 조회되지 않는다.
OLD_TABLE_TYPE_ALL = 'ALL'
NEW_TABLE_TYPE_MF = 'MF'


def forward_all_to_mf(apps, schema_editor):
    PhotoStepChangeLog = apps.get_model('api', 'PhotoStepChangeLog')
    PhotoStepChangeLog.objects.filter(table_type=OLD_TABLE_TYPE_ALL).update(table_type=NEW_TABLE_TYPE_MF)


def backward_mf_to_all(apps, schema_editor):
    PhotoStepChangeLog = apps.get_model('api', 'PhotoStepChangeLog')
    PhotoStepChangeLog.objects.filter(table_type=NEW_TABLE_TYPE_MF).update(table_type=OLD_TABLE_TYPE_ALL)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_photostepchangelog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photosteps1",
            options={
                "verbose_name": "line1 {{request.col_step}} 정보(PMAINF)",
                "verbose_name_plural": "line1 {{request.col_step}} 정보(PMAINF) 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="photosteps3",
            options={
                "verbose_name": "line3 {{request.col_step}} 정보(PMAINF)",
                "verbose_name_plural": "line3 {{request.col_step}} 정보(PMAINF) 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="photosteps4",
            options={
                "verbose_name": "line4 {{request.col_step}} 정보(PMAINF)",
                "verbose_name_plural": "line4 {{request.col_step}} 정보(PMAINF) 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="photosteps5",
            options={
                "verbose_name": "line5 {{request.col_step}} 정보(PMAINF)",
                "verbose_name_plural": "line5 {{request.col_step}} 정보(PMAINF) 목록",
            },
        ),
        migrations.AlterField(
            model_name="photostepchangelog",
            name="table_type",
            field=models.CharField(
                choices=[("MF", "PMAINF"), ("OV", "POVLAY"), ("CD", "XXXXXX")],
                max_length=10,
                verbose_name="테이블 구분",
            ),
        ),
        migrations.RunPython(forward_all_to_mf, backward_mf_to_all),
    ]
