# Generated by Django 4.2.13 on 2026-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_alter_mailnotification_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="r_skip_round",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="R 생략 회차"
            ),
        ),
    ]
