# Generated by Django 4.2.13 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_requestdocument_r_skip_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="layer_drift_detected",
            field=models.BooleanField(default=False, verbose_name="레이어 정보 변경 감지 여부"),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="layer_drift_detail",
            field=models.TextField(blank=True, verbose_name="레이어 정보 변경 상세(JSON)"),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="layer_drift_checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="레이어 정보 변경 감지 확인 시각"
            ),
        ),
    ]
