# Generated by Django 4.2.13 on 2026-09-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_requestdocument_layer_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="extra_layer_snapshot",
            field=models.TextField(
                blank=True, verbose_name="XXXXXX 레이어 상신 시점 스냅샷(JSON)"
            ),
        ),
    ]
