# Generated by Django 4.2.13 on 2026-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_requestdocument_layer_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionsnapshot",
            name="is_overseas",
            field=models.BooleanField(default=False, verbose_name="해외 의뢰서 여부"),
        ),
        migrations.AddField(
            model_name="requestdocument",
            name="is_overseas",
            field=models.BooleanField(default=False, verbose_name="해외 의뢰서 여부"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("NONE", "NONE"),
                    ("PL", "PL"),
                    ("PL_GL", "PL_GL"),
                    ("TE_R", "TE_R"),
                    ("TE_P", "TE_P"),
                    ("TE_J", "TE_J"),
                    ("TE_O", "TE_O"),
                    ("TE_E", "TE_E"),
                    ("MASTER", "MASTER"),
                ],
                default="NONE",
                max_length=10,
                verbose_name="역할",
            ),
        ),
    ]
