# Generated by Django 4.2.13 on 2026-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_requestdocument_layer_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tokens_valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="토큰 유효 시작 시각"
            ),
        ),
    ]
