# Generated by Django 4.2.13 on 2026-09-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_requestdocument_layer_drift"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lineid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="라인 ID"
                    ),
                ),
                (
                    "partid",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Part ID"
                    ),
                ),
                (
                    "m",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="M"
                    ),
                ),
                (
                    "s",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="S"
                    ),
                ),
                (
                    "last_synced",
                    models.DateTimeField(auto_now=True, verbose_name="동기화 시각"),
                ),
            ],
            options={
                "verbose_name": "MAP 테이블 캐시",
                "verbose_name_plural": "MAP 테이블 캐시 목록",
            },
        ),
    ]
