# Generated by Django 4.2.13 on 2026-09-22 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_overseas_pl_role"),
        ("api", "0046_maptable"),
    ]

    operations = []
