# Generated by Django 4.2.13 on 2026-10-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_merge_0045_overseas_pl_role_0046_maptable"),
    ]

    operations = [
        migrations.AddField(
            model_name="rejectionsnapshot",
            name="layer_drift_detected",
            field=models.BooleanField(
                default=False, verbose_name="레이어 정보 변경 감지 여부"
            ),
        ),
        migrations.AddField(
            model_name="rejectionsnapshot",
            name="layer_drift_detail",
            field=models.TextField(
                blank=True, verbose_name="레이어 정보 변경 상세(JSON)"
            ),
        ),
    ]
