# Generated by Django 4.2.13 on 2026-10-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_squashed_0048_rejectionsnapshot_layer_drift_detected"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="review_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="검토중 시작일시"
            ),
        ),
    ]
