# Generated by Django 4.2.13 on 2026-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_approvalstep_review_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestdocument",
            name="sales_agreer_none_reasons",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="합의자 미지정 사유(회차별)"
            ),
        ),
    ]
