# Generated by Django 4.2.13 on 2026-10-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_mailnotification_route_member_removed"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerSdException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table",
                    models.CharField(
                        choices=[("J", "J"), ("O", "O")],
                        max_length=1,
                        verbose_name="대상 표",
                    ),
                ),
                (
                    "process_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Process ID",
                    ),
                ),
                (
                    "sp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="SP(STEPSEQ)",
                    ),
                ),
                (
                    "sd_number",
                    models.CharField(max_length=100, verbose_name="SD 첫 숫자"),
                ),
                ("layerid", models.CharField(max_length=100, verbose_name="Layer")),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="등록자 ID"
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="등록자 이름",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
            options={
                "verbose_name": "J/O-layer SD-Layer 검사 예외",
                "verbose_name_plural": "J/O-layer SD-Layer 검사 예외",
                "ordering": ["table", "-created_at"],
                "unique_together": {
                    ("table", "process_id", "sp", "sd_number", "layerid")
                },
            },
        ),
    ]
