# Generated by Django 4.2.13 on 2026-10-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_layersdexception"),
    ]

    operations = [
        migrations.AddField(
            model_name="layersdexception",
            name="sd",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="SD"
            ),
        ),
    ]
